apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-service-be-role
rules:
- apiGroups: [""]
  resources: ["pods","jobs"]
  verbs: ["get","list","watch","create","delete"]
- apiGroups: ["scheduling.run.ai"]
  resources: ["podgroups","queues","bindrequests","podgroups/status","bindrequests/status"]
  verbs: ["get","list","watch","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: a87-binding
subjects:
- kind: ServiceAccount
  name: gpu-service-be-account
  namespace: gpu-service
roleRef:
  kind: ClusterRole
  name: gpu-service-be-role
  apiGroup: rbac.authorization.k8s.io