{{- if .Values.queues.gpuA40.enabled }}
apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
  name: gpu-queue-a40
spec:
  priority: 100
  resources:
    cpu:
      quota: 0
      overQuotaWeight: 0
    gpu:
      quota: 2
      overQuotaWeight: 1
    memory:
      quota: -1
      overQuotaWeight: 1
{{- end }}