apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  labels:
    app.kubernetes.io/name: {{ include "gpu-service-be.fullname" . }}
type: Opaque
data:
  accesskey: {{ .Values.secret.minio.accessKey | b64enc }}
  secretkey: {{ .Values.secret.minio.secretKey | b64enc }}